### ISSUE TITLE
Error: ER_NO_BINARY_LOGGING: You are not using binary logging

### ISSUE THREAD

**Issue by amolvppawar** [bhaikaju/realtimeapp#1]
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
Server running on port 5000
Error: ER_NO_BINARY_LOGGING: You are not using binary logging
    at Query.Sequence._packetToError (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Protocol._enqueue (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\Connection.js:198:25)
    at ZongJi._findBinlogEnd (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\@rodrigogs\zongji\index.js:169:23)
    at nextMethod (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\@rodrigogs\zongji\index.js:98:22)
    at C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\@rodrigogs\zongji\index.js:102:9
    at Query.<anonymous> (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\@rodrigogs\zongji\index.js:159:9)
    at Query.<anonymous> (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\Ams\PhpstormProjects\realtimeappAngular\node_modules\mysql\lib\protocol\sequences\Query.js:149:8) {
  code: 'ER_NO_BINARY_LOGGING',
  errno: 1381,
  sqlMessage: 'You are not using binary logging',
  sqlState: 'HY000',
  index: 0,
  sql: 'SHOW BINARY LOGS'

**Comment by moradiyainfo** [comment]
Set the log-bin variable in your MySQL configuration file, then restart MySQL.

An example my.cnf (on Linux/unix) or my.ini (on Windows) would look like:

[client]
...

[mysqld]
...
log-bin=mysql-bin
---
